/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import javax.swing.JOptionPane;

/**
 *
 * @author Haidar
 */
public class Swing1841720194Haidar extends javax.swing.JFrame {
    
    private String nama, nim, jeniskelamin, info, jurusan, matakuliah,semester;
    /**
     * Creates new form Swing
     */
    public Swing1841720194Haidar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ljudul = new javax.swing.JLabel();
        lnama = new javax.swing.JLabel();
        lnim = new javax.swing.JLabel();
        innama = new javax.swing.JTextField();
        innim = new javax.swing.JTextField();
        jenkel = new javax.swing.JLabel();
        rblaki = new javax.swing.JRadioButton();
        rbcewe = new javax.swing.JRadioButton();
        lmatkul = new javax.swing.JLabel();
        cbdistri = new javax.swing.JCheckBox();
        cbpbo = new javax.swing.JCheckBox();
        ljurusan = new javax.swing.JLabel();
        lisjurusan = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lsemester = new javax.swing.JLabel();
        cbsemester = new javax.swing.JComboBox<>();
        butreset = new javax.swing.JButton();
        buttampil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ljudul.setText("Data Mahasiswa");

        lnama.setText("Nama");

        lnim.setText("Nim");

        innama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                innamaActionPerformed(evt);
            }
        });

        innim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                innimActionPerformed(evt);
            }
        });

        jenkel.setText("Jenis Kelamin");

        rblaki.setText("Laki");

        rbcewe.setText("cewe");

        lmatkul.setText("Mata Kuliah");

        cbdistri.setText("Distribusi");
        cbdistri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdistriActionPerformed(evt);
            }
        });

        cbpbo.setText("PBO");
        cbpbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpboActionPerformed(evt);
            }
        });

        ljurusan.setText("Jurusan");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "informatika", "manajemen"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lisjurusan.setViewportView(jList1);

        lsemester.setText("Semester");

        cbsemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1", "S2"}));

        butreset.setText("Clear");
        butreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butresetActionPerformed(evt);
            }
        });

        buttampil.setText("tampil");
        buttampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttampilActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(ljurusan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lisjurusan))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lmatkul)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbdistri)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbpbo)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lnim)
                                    .addGap(18, 18, 18)
                                    .addComponent(innim))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lnama)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(innama, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jenkel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rblaki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbcewe))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lsemester)
                                .addGap(18, 18, 18)
                                .addComponent(cbsemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(ljudul)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butreset, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttampil, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ljudul)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnama)
                            .addComponent(innama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnim)
                            .addComponent(innim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jenkel)
                                .addComponent(rblaki))
                            .addComponent(rbcewe))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lmatkul)
                            .addComponent(cbdistri)
                            .addComponent(cbpbo))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ljurusan)
                            .addComponent(lisjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lsemester)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbsemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butreset, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttampil)))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void innamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_innamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_innamaActionPerformed

    private void innimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_innimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_innimActionPerformed

    private void cbdistriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdistriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbdistriActionPerformed

    private void cbpboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbpboActionPerformed

    private void butresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butresetActionPerformed
        // TODO add your handling code here:
        
        innama.setText("");
        innim.setText("");
        cbdistri.setSelected(false);
        cbpbo.setSelected(false);
        jTextArea1.setText("");
    }//GEN-LAST:event_butresetActionPerformed

    private void buttampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttampilActionPerformed
        // TODO add your handling code here:
        nama = innama.getText();
        nim = innim.getText();
        if(cbdistri.isSelected()){
            matakuliah =  "distri";
        }
        if(cbpbo.isSelected()){
            matakuliah += " pbo";
        }
        
        if(rblaki.isSelected()){
            jeniskelamin = "cewe";
        }
        if(rblaki.isSelected()){
            jeniskelamin = "cowo";
        }
        
        jurusan = jList1.getSelectedValue().toString();
        semester = cbsemester.getSelectedItem().toString();
        
        info = "nama    :"+nama+"\n";
        info +="nim     :"+nim+"\n";
        info +="Jk     :"+jeniskelamin+"\n";
        info +="Jur     :"+jurusan+"\n";
        info +="Sem     :"+semester+"\n";
        info +="matkul  :"+matakuliah+"\n";
        
        jTextArea1.setText(info);
        JOptionPane.showMessageDialog(null, info);
    }//GEN-LAST:event_buttampilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Swing1841720194Haidar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Swing1841720194Haidar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Swing1841720194Haidar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Swing1841720194Haidar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Swing1841720194Haidar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butreset;
    private javax.swing.JButton buttampil;
    private javax.swing.JCheckBox cbdistri;
    private javax.swing.JCheckBox cbpbo;
    private javax.swing.JComboBox<String> cbsemester;
    private javax.swing.JTextField innama;
    private javax.swing.JTextField innim;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jenkel;
    private javax.swing.JScrollPane lisjurusan;
    private javax.swing.JLabel ljudul;
    private javax.swing.JLabel ljurusan;
    private javax.swing.JLabel lmatkul;
    private javax.swing.JLabel lnama;
    private javax.swing.JLabel lnim;
    private javax.swing.JLabel lsemester;
    private javax.swing.JRadioButton rbcewe;
    private javax.swing.JRadioButton rblaki;
    // End of variables declaration//GEN-END:variables
}
